name: Cache Boost
description: Caches Boost for an OS and a Boost minor version
inputs:
  boost_minor:
    required: true
  os:
    required: true
outputs:
  cache-hit:
    description: "Indicates if caching was successful"
    value: ${{ steps.cache-boost.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
  - name: Cache Boost
    uses: actions/cache@v3
    id: cache-boost
    env:
      cache-name: cache-boost
    with:
      path: ${{ github.workspace }}/boost
      key: ${{ inputs.os }}-boost-${{ inputs.boost_minor }}
