name: Cache Boost
description: Caches Boost for an OS and a Boost minor version
inputs:
  boost_minor:
    required: true
  os:
    required: true

runs:
  using: "composite"
  steps:
  - name: Cache Boost
    uses: actions/cache@v3
    env:
      cache-name: cache-boost
    with:
      path: ${{ github.workspace }}/boost
      key: ${{ inputs.os }}-boost-${{ inputs.boost_minor }}
