name: Run C++ tests

on:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-14"]
        boost_minor: [85]

    steps:
    - uses: actions/checkout@v3
      # with:
      #   submodules: true

    - name: FIXME manual submodule checkout 🤌
      run: |
        git config --global url.https://x-access-token:${{ secrets.GH_PAT }}@github.com/BlueBrain/brain-indexer-test-data.insteadOf https://github.com/BlueBrain/brain-indexer-test-data.git
        git submodule update --init --recursive

    - name: Install Ubuntu system dependencies
      if: startsWith(matrix.os, 'ubuntu-')
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build libopenmpi-dev

    - name: Install MacOs system dependencies
      if: startsWith(matrix.os, 'macos-')
      run: |
        brew install ninja openmpi

    - name: Cache Boost
      id: cache-boost
      uses: actions/cache@v3
      env:
        cache-name: cache-boost
      with:
        path: ${{ github.workspace }}/boost
        key: ${{ matrix.os }}-boost-${{ matrix.boost_minor }}

    - name: Configure and build
      run: |
        cmake -B build -G Ninja -DCMAKE_PREFIX_PATH=$PWD/boost .
        cmake --build build

    - name: Set up MPI for Github Actions
      run: |
        mkdir -p "$HOME/.openmpi"
        cat <<EOF > "$HOME/.openmpi/mca-params.conf"
        rmaps_base_oversubscribe = true
        rmaps_default_mapping_policy = :oversubscribe
        EOF

    - name: Run CTest
      run: |
        ctest --test-dir build --output-on-failure
