name: Run all tests

on:
  push:
    branches: ['main']
    tags: ['v?[0-9]+.[0-9]+.[0-9]+']
  pull_request:

jobs:
  cache_boost:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-14"]
        boost_minor: [85]

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/boost-cache
      id: cache-boost
      with:
        os: ${{ matrix.os }}
        boost_minor: ${{ matrix.boost_minor }}

    - name: Install Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        wget -qO- https://boostorg.jfrog.io/artifactory/main/release/1.${{ matrix.boost_minor }}.0/source/boost_1_${{ matrix.boost_minor }}_0.tar.bz2 | tar xjf -
        cd boost_1_${{ matrix.boost_minor }}_0
        ./bootstrap.sh
        ./b2 --prefix=../boost --with-serialization --with-filesystem --with-test install

  test_cxx:
    uses: ./.github/workflows/ctest.yml
    secrets: inherit
    needs: [cache_boost]

  test_python:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    needs: [cache_boost]

  publish:
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    needs: [cache_boost]
