name: Run Python tests and lint

on:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-14"]
        boost_minor: [85]
        python-version: ['3.11', '3.12']
        toxenv: ['py3']
        include:
          - os: 'ubuntu-latest'
            python-version: '3.12'
            toxenv: 'flake8'

    steps:
    - uses: actions/checkout@v3
      # with:
      #   submodules: true

    - name: FIXME manual submodule checkout 🤌
      run: |
        git config --global url.https://x-access-token:${{ secrets.GH_PAT }}@github.com/BlueBrain/brain-indexer-test-data.insteadOf https://github.com/BlueBrain/brain-indexer-test-data.git
        git submodule update --init --recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Ubuntu system dependencies
      if: startsWith(matrix.os, 'ubuntu-')
      run: |
        sudo apt-get update
        sudo apt-get install libopenmpi-dev

    - name: Install MacOs system dependencies
      if: startsWith(matrix.os, 'macos-')
      run: |
        brew install openmpi

    - name: Cache Boost
      id: cache-boost
      uses: actions/cache@v3
      env:
        cache-name: cache-boost
      with:
        path: ${{ github.workspace }}/boost
        key: ${{ matrix.os }}-boost-${{ matrix.boost_minor }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox

    - name: Test with tox
      run: |
        export BOOST_ROOT=$PWD/boost
        export CMAKE_PREFIX_PATH=$PWD/boost
        tox -e ${{ matrix.toxenv }}
